app1/urls.py
from django.urls import path, re_path
from django.urls import converters, register_converter


class CategoryConverter(object):
    regex = r'\w+|(\w+\+\w+)+'  # 这里的正则表达式 变量名称 必须是 regex 不然Django不能识别

    def to_python(self, value):
        '''
        将 python+django+flask 处理成 ['python', 'django', 'flask']
        '''
        result = value.split('+')
        return result

    def to_url(self, value):
        '''
        将 ['python', 'django', 'flask'] 处理成 python+django+flask
        '''
        if isinstance(value, list):
            result = '+'.join(value)
            return result
        else:
            raise RuntimeError('转换URL的时候分类参数必须为list类型')


register_converter(CategoryConverter, 'cate')  # 将自定义的转换通过 register_converter 器注册到 Django 命名为 cate

from app1 import views

app_name = 'app1'

urlpatterns = [
    path('', views.index_django_study, name='django_study_index'),
    path('index/', views.index, name='index'),

    # url中传递参数给视图函数
    path('args-1/<int:id>/', views.url_args1, name='args-1'),
    path('args-2/', views.url_args2, name='args-2'),

    # url命名与url反转
    path('args-3/', views.url_args3, name='args-3'),
    path('args-4/', views.url_args4, name='args-4'),
    path('args-5/', views.url_args5, name='args-5'),

    # 实例命名空间
    path('args-6/', views.url_args6, name='args-6'),
    path('args-7/', views.url_args7, name='args-7'),

    # 使用re_path
    re_path(r're_path/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/', views.url_args8, name='re-path'),

    # url带参数反转
    path('args-9/', views.url_args9, name='args-9'),
    path('args-10/<int:id>/<int:page>/', views.url_args10, name='args-10'),

    # url携带查询字符串参数反转
    path('args-11/', views.url_args11, name='args-11'),
    path('args-12/', views.url_args12, name='args-12'),

    # 自定义path转换器
    path('args-13/<cate:categories>/', views.url_args13, name='args-13'),
    path('args-14/', views.url_args14, name='args-14'),

    # URL映射的时候指定默认参数
    path('args-15/<int:page>/', views.url_args15, name='args-15'),
    path('args-15-1/', views.url_args15, name='args-15-1'),

]

app2/urls.py
from django.urls import path

from app2 import views

app_name = 'app2'

urlpatterns = [
    # 模版渲染的两种方式
    path('template1/', views.template1, name='app2-1'),
    path('template2/', views.template2, name='app2-2'),

    # 模版变量的使用
    path('template3/', views.template3, name='app2-3'),

    # for标签的使用
    path('template4/', views.template4, name='app2-4'),

    # with标签的使用
    path('template5/', views.template5, name='app2-5'),

    # url标签的使用
    path('template6/', views.template6, name='app2-6'),
    path('template7/<str:id>/<int:page>/', views.template7, name='app2-7'),
    path('template8/', views.template8, name='app2-8'),

    # autoescape标签的使用
    path('template9/', views.template9, name='app2-9'),

    # verbatim标签的使用
    path('template10/', views.template10, name='app2-10'),

    # 常见的模版顾虑器
    path('template11/', views.template11, name='app2-11'),

    # 自定义模版过滤器
    path('template12/', views.template12, name='app2-12'),

    # 模版优化-引入模版
    path('template13/', views.template13, name='app2-13'),

    # 模版优化-模版继承
    path('template14/', views.template14, name='app2-14'),

    # 加载静态文件
    path('template15/', views.template15, name='app2-15'),
    path('template16/', views.template16, name='app2-16'),

]

django_study/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from app1 import inclued_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('app1.urls')),

    # ------------- URL与视图 -------------
    path('app1/', include('app1.urls', namespace='app1-a')),
    # 实例命名空间: 同一个app1下出现了两个实例app1、app1-1
    path('app1-1/', include('app1.urls', namespace='app1-b')),
    # 将 子URL 放到 include 中
    path('app1-2/', include([
        path('include/', inclued_views.app1_inclued, name='include_path')
    ])),

    # ------------- URL与视图 -------------
    path('app2/', include('app2.urls')),

    # ------------- Django 数据库 -------------
    path('app3/', include('app3.urls')),

    # ------------- Django 视图高级 -------------
    path('app4/', include('app4.urls')),

    # ------------- Django 状态码错误处理 -------------
    path('error/', include('error.urls')),

    # ------------- Django 表单 -------------
    path('app5/', include('app5.urls')),

    # ------------- Django 文件上传 -------------
    path('app6/', include('app6.urls')),

    # ------------- Django 缓存 -------------
    path('app7/', include('app7.urls')),

    # ------------- Django cookie 和 session -------------
    path('app8/', include('app8.urls')),

    # ------------- Django 上下文处理器 -------------
    path('app9/', include('app9.urls')),

    # ------------- Django 中间件 -------------
    path('app10/', include('app10.urls')),

    # ------------- Django CSRF攻击 -------------
    path('app11/', include('app11.urls')),

    # ------------- Django XXS攻击 -------------
    path('app12/', include('app12.urls')),

    # ------------- Django 验证和授权（一） -------------
    path('app13/', include('app13.urls')),

    # ------------- Django rest_framework -------------
    path('app14/', include('app14.urls')),

    # ------------- Django 验证和授权（二） -------------
    path('app15/', include('app15.urls')),

    # ------------- 页面显示Markdown -------------
    path('app16/', include('app16.urls')),

    # ------------- Django 日志 -------------
    path('app17/', include('app17.urls')),

    # ------------- Django 信号 -------------
    path('app18/', include('app18.urls')),

    # ------------- FastDFS -------------
    path('app19/', include('app19.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from app14.urls import router as app14

restful_url = [
    path('api/app14/', include(app14.urls)),
]

urlpatterns = urlpatterns + restful_url

app2/models.py
from django.db import models

# Create your models here.

app2/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse
from django.template.loader import render_to_string
from datetime import datetime


# Create your views here.


def template1(request):
    ''' render_to_string 渲染模版 '''
    html = render_to_string('app2-1.html')
    return HttpResponse(html)


def template2(request):
    ''' render 渲染模版'''
    return render(request, 'app2-1.html')


def template3(request):
    ''' 模版变量的使用'''

    persion = Persion('Rong Ku')  # 传递一个对象
    ku_rong = {
        'age': 18
    }  # 传递一个字典
    like1 = ['python', 'django']  # 传递一个列表
    like2 = ('movie', 'kendo')  # 传递一个元组

    context = {
        'username': 'ku_rong',
        'persion': persion,
        'ku_rong': ku_rong,
        'like1': like1,
        'like2': like2
    }
    return render(request, 'app2/app2-2.html', context=context)


# ------------------------ for标签 ------------------------


def template4(request):
    context = {
        'examples': ['python', 'django', 'flask'],
        'persion': {
            'name': 'ku_rong',
            'age': 18,
            'work': 'coder'
        },
        'books': [
            {
                'name': '三国演义',
                'author': '罗贯中',
                'price': 120
            },
            {
                'name': '水浒传',
                'author': '施耐庵',
                'price': 100
            },
            {
                'name': '西游记',
                'author': '吴承恩',
                'price': 90
            },
            {
                'name': '红楼梦',
                'author': '曹雪芹',
                'price': 110
            },
        ],
        'comments': []
    }
    return render(request, 'app2/app2-3for标签.html', context=context)


# ------------------------ for标签 ------------------------


def template5(request):
    context = {
        'persons': ['ku_rong', 'ronggege']
    }
    return render(request, 'app2/app2-5with标签.html', context=context)


# ------------------------ url标签 ------------------------


def template6(request):
    context = {'page': 9, 'id': '001'}
    return render(request, 'app2/app2-6url标签.html', context=context)


def template7(request, id, page):
    context = {
        'id': id,
        'page': page,
        'next_url': reverse('app2:app2-6')
    }
    return render(request, 'app2/app2-7url标签.html', context=context)


def template8(request):
    next = request.GET.get('next')
    context = {'next': next}
    return render(request, 'app2/app2-8url标签.html', context=context)


# ------------------------ autoescape标签 ------------------------

def template9(request):
    context = {
        'url': "<p><a href='https://www.baidu.com/'>百度</a></p>"
    }
    return render(request, 'app2/app2-9autoescape标签.html', context=context)


# ------------------------ verbatim标签 ------------------------

def template10(request):
    context = {
        'hello': 'ku_rong'
    }
    return render(request, 'app2/app2-10verbatim标签.html', context=context)


# ------------------------ 常见的模版过滤器 ------------------------


def template11(request):
    context = {
        'v1': ['apple', 'banana'],
        'v2': ['chestnut', 'coconut'],
        'v3': 'apricot almond ...',
        'v4': '',
        'v5': None,
        'v6': ['blackberry', 'blueberry'],
        'v7': [30.260, 30.3222, 30.00],
        'v8': ['Banana', 'Bitter orange'],
        'v9': "<script>alert('Apricot');</script>",
        'v10': '<p>apricot almond</p>',
        'v11': 'apple apricot almond banana berry blackberry blueberry Bitter orange',
        'v12': '<p>apple apricot almond banana berry blackberry blueberry Bitter orange</p>',
        'now': datetime.now(),
    }
    return render(request, 'app2/app2-11常见的过滤器.html', context=context)


# ------------------------ 自定义模版过滤器 ------------------------

def template12(request):
    context = {
        'v1': 'ku_',
        'v2': 'rong',
        'v3': 'Django',
        'v4': 'Flask',
        'v5': 'Rong',
        'v6': 'ku_rong'
    }
    return render(request, 'app2/app2-12自定义模版过滤器.html', context=context)


# ------------------------ 模版优化-引入模版 ------------------------
def template13(request):
    context = {'username': 'ku_rong'}
    return render(request, 'app2/app2-13模版优化-引入模版.html', context=context)


# ------------------------ 模版优化-模版继承 ------------------------
def template14(request):
    context = {'username': 'ku_rong', 'age': 18}
    return render(request, 'app2/app2-14模版优化-模版继承.html', context=context)


# ------------------------ 加载静态文件 ------------------------
def template15(request):
    context = {}
    return render(request, 'app2/app2-15加载静态文件.html', context=context)


def template16(request):
    context = {}
    return render(request, 'app2/app2-15加载静态文件static内置.html', context=context)


class Persion(object):
    def __init__(self, username):
        self.name = username

templates/app2/app2-10verbatim标签.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>verbatim标签</title>
</head>
<body>
<h1>verbatim标签</h1>
{% verbatim %}
<p>{{ hello }}</p>
{% endverbatim %}
</body>
</html>

templates/app2/app2-11常见的过滤器.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>常见的过滤器</title>
</head>
<body>
    <h1>常见的模版过滤器</h1>
    <h1>add 过滤器</h1>
    {{ v1|add:v2 }}
    <h1>cut 过滤器</h1>
    {{ v3|cut:' ...' }}
    <h1>date 过滤器</h1>
    {{ now|date:'y M d D g a' }}
    <h1>default 过滤器</h1>
    {{ v4|default:'betelnut' }}
    <h1>default_if_none 过滤器</h1>
    {{ v5|default_if_none:'berry' }}
    <h1>first 过滤器</h1>
    {{ v6|first }}
    <h1>last 过滤器</h1>
    {{ v6|last }}
    <h1>floatformat 过滤器</h1>
    {{ v7.0|floatformat }} {{ v7.1|floatformat }} {{ v7.2|floatformat }}
    {{ v7.0|floatformat:'3' }} {{ v7.1|floatformat:'3' }} {{ v7.2|floatformat:'3' }}
    <h1>join 过滤器</h1>
    {{ v8|join:' and ' }}
    <h1>length 过滤器</h1>
    {{ v8|length }}
    <h1>upper 过滤器</h1>
    {{ v8.0|upper }}
    <h1>lower 过滤器</h1>
    {{ v8.0|lower }}
    <h1>random 过滤器</h1>
    {{ v8|random }}
    <h1>safe 过滤器</h1>
    {{ v9|safe }}
    <h1>slice 过滤器</h1>
    {{ v8|slice:"1:" }} {{ v3|slice:":-4" }}
    <h1>striptags 过滤器</h1>
    {{ v10|striptags }}
    <h1>truncatechars 过滤器</h1>
    {{ v11|truncatechars:'20' }}
    <h1>truncatechars_html 过滤器</h1>
    {{ v12|truncatechars_html:'20' }}
</body>
</html>

templates/app2/app2-12自定义模版过滤器.html
{% load customize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>自定义模版过滤器</title>
</head>
<body>
    <h1>自定义模版过滤器</h1>
    <h2>Name: {{ v1|str_joint:v2 }}</h2>
    <h2>Like: {{ v3|list_joint:v4 }}</h2>
    <h2>{{ v5|hello }}</h2>
    <h2>{{ v6|hello:'最帅的小哥哥是：' }}</h2>
</body>
</html>

templates/app2/app2-13模版优化-引入模版01.html
<header>
    <h1>This is include header</h1>
</header>

templates/app2/app2-13模版优化-引入模版02.html
<footer>
    <h1>This is include foot</h1>
</footer>

templates/app2/app2-13模版优化-引入模版03.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Hello {{ username }}, This is include username</h1>
    <h1>Age: {{ age }}</h1>
</body>
</html>

templates/app2/app2-14模版优化-模版继承base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>模版优化-模版继承</title>
</head>
<body>
    <header>
        <h1>This is base header</h1>
    </header>
    {% block content %}
    Hello {{ username }}! I am base html
    {% endblock %}
    <footer>
        <h1>This is base footer</h1>
    </footer>
</body>
</html>

templates/app2/app2-15加载静态文件.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>加载静态文件</title>
</head>
<body>
<h1>加载app2/static/app2/Django.png</h1>
<img src="{% static 'app2/Django.png' %}" alt="">
<h1>加载/static/app2/Python.png</h1>
<img src="{% static 'app2/Python.png' %}" alt="">
<h1>加载/static/world.jpeg</h1>
<img src="{% static 'world.jpeg' %}" alt="">
</body>
</html>

templates/app2/app2-15加载静态文件static内置.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>static 变成内置标签，不用load</title>
</head>
<body>
<h1>加载app2/static/app2/Django.png</h1>
<img src="{% static 'app2/Django.png' %}" alt="">
<h1>加载/static/app2/Python.png</h1>
<img src="{% static 'app2/Python.png' %}" alt="">
<h1>加载/static/world.jpeg</h1>
<img src="{% static 'world.jpeg' %}" alt="">
</body>
</html>

templates/app2/app2-2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>模版变量的使用</title>
</head>
<body>
    <h1>hello {{ username }}</h1>
    {# persion.name 获取对象的属性， ku_rong.age 获取字典的value， like1.1，like2.0 获取字典和元组中的值 #}
    <h2>hello, my name is {{ persion.name }}, {{ ku_rong.age }} years old, like {{ like1.1 }} and {{ like2.0 }}</h2>
</body>
</html>

templates/app2/app2-3for标签.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>for 标签</title>
</head>
<body>
    <h1>for 标签的使用</h1>
    <u>
        {% for example in examples %}
            <li>{{ example }}</li>
        {% endfor %}
    </u>
    <h1>反向遍历</h1>
    <ul>
        {% for book in books reversed%}
            <li>{{ book }}</li>
        {% endfor %}
    </ul>
    <h1>遍历字典</h1>
    <ul>
        {% for key, value in persion.items %}
            <li>{{ key }} : {{ value }}</li>
        {% endfor %}

        {% for key in persion.keys %}
            <li>{{ key }}</li>
        {% endfor %}

        {% for value in persion.values %}
            <li>{{ value }}</li>
        {% endfor %}
    </ul>
    <h1>其它用法</h1>
    <table>
        <thead>
        <tr>
            <td>subscript</td>
            <td>name</td>
            <td>author</td>
            <td>price</td>
        </tr>
        </thead>
        <tbody>
            {% for book in books %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ book.name }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.price }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <table>
        <thead>
        <tr>
            <td>subscript</td>
            <td>name</td>
            <td>author</td>
            <td>price</td>
        </tr>
        </thead>
        <tbody>
            {% for book in books %}
                <tr>
                    <td>{{ forloop.counter0 }}</td>
                    <td>{{ book.name }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.price }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <table>
        <thead>
        <tr>
            <td>subscript</td>
            <td>name</td>
            <td>author</td>
            <td>price</td>
        </tr>
        </thead>
        <tbody>
            {% for book in books reversed %}
                <tr>
                    <td>{{ forloop.revcounter }}</td>
                    <td>{{ book.name }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.price }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <table>
        <thead>
        <tr>
            <td>subscript</td>
            <td>name</td>
            <td>author</td>
            <td>price</td>
        </tr>
        </thead>
        <tbody>
            {% for book in books reversed %}
                <tr>
                    <td>{{ forloop.revcounter0 }}</td>
                    <td>{{ book.name }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.price }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <table>
        <thead>
        <tr>
            <td>subscript</td>
            <td>name</td>
            <td>author</td>
            <td>price</td>
        </tr>
        </thead>
        <tbody>
            {% for book in books reversed %}
                {% if forloop.first %}
                    <tr style="background: red;">
                {% elif forloop.last %}
                    <tr style="background: pink;">
                {% else %}
                    <tr>
                {% endif %}
                    <td>{{ forloop.revcounter0 }}</td>
                    <td>{{ book.name }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.price }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <ul>
        {% for comment in comments %}
            <li>{{ comment }}</li>
        {% empty %}
            <li>没有任何评论</li>
        {% endfor %}

    </ul>
</body>
</html>

templates/app2/app2-5with标签.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>with 标签</title>
</head>
<body>
    <h1>with 标签的用法</h1>
    {% with shuaide=persons.1  %}
        <p>{{ shuaide }}</p>
    {% endwith %}

    {% with persons.0 as zuishuaide %}
        <p>{{ zuishuaide }}</p>
    {% endwith %}
</body>
</html>

templates/app2/app2-7url标签.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>URL标签</title>
</head>
<body>
    <h1>URL标签</h1>
    <p>page={{ page }} id={{ id }}</p>
    <p><a href="{% url 'app2:app2-8' %}?next={{ next_url }}">查询字符串跳转</a></p>
</body>
</html>

templates/app2/app2-8url标签.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>URL标签</title>
</head>
<body>
    <h1>URL标签</h1>
    <p>{{ next }}</p>
    <p><a href="{{ next }}">一般跳转</a></p>
</body>
</html>