app1/urls.py
from django.urls import path, re_path
from django.urls import converters, register_converter


class CategoryConverter(object):
    regex = r'\w+|(\w+\+\w+)+'  # 这里的正则表达式 变量名称 必须是 regex 不然Django不能识别

    def to_python(self, value):
        '''
        将 python+django+flask 处理成 ['python', 'django', 'flask']
        '''
        result = value.split('+')
        return result

    def to_url(self, value):
        '''
        将 ['python', 'django', 'flask'] 处理成 python+django+flask
        '''
        if isinstance(value, list):
            result = '+'.join(value)
            return result
        else:
            raise RuntimeError('转换URL的时候分类参数必须为list类型')


register_converter(CategoryConverter, 'cate')  # 将自定义的转换通过 register_converter 器注册到 Django 命名为 cate

from app1 import views

app_name = 'app1'

urlpatterns = [
    path('', views.index_django_study, name='django_study_index'),
    path('index/', views.index, name='index'),

    # url中传递参数给视图函数
    path('args-1/<int:id>/', views.url_args1, name='args-1'),
    path('args-2/', views.url_args2, name='args-2'),

    # url命名与url反转
    path('args-3/', views.url_args3, name='args-3'),
    path('args-4/', views.url_args4, name='args-4'),
    path('args-5/', views.url_args5, name='args-5'),

    # 实例命名空间
    path('args-6/', views.url_args6, name='args-6'),
    path('args-7/', views.url_args7, name='args-7'),

    # 使用re_path
    re_path(r're_path/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/', views.url_args8, name='re-path'),

    # url带参数反转
    path('args-9/', views.url_args9, name='args-9'),
    path('args-10/<int:id>/<int:page>/', views.url_args10, name='args-10'),

    # url携带查询字符串参数反转
    path('args-11/', views.url_args11, name='args-11'),
    path('args-12/', views.url_args12, name='args-12'),

    # 自定义path转换器
    path('args-13/<cate:categories>/', views.url_args13, name='args-13'),
    path('args-14/', views.url_args14, name='args-14'),

    # URL映射的时候指定默认参数
    path('args-15/<int:page>/', views.url_args15, name='args-15'),
    path('args-15-1/', views.url_args15, name='args-15-1'),

]

app4/urls.py
from django.urls import path
from django.views.generic import TemplateView

from app4 import views

app_name = 'app4'

urlpatterns = [
    # ---------------- 限制请求 method 的装饰器 ----------------
    path('method-1/', views.method_get, name='app4-1'),
    path('method-2/', views.method_post, name='app4-2'),
    path('method-3/', views.method_get_post, name='app4-3'),

    # ---------------- 重定向 ----------------
    path('rediction-1/', views.rediction_1, name='app4-4'),
    path('rediction-2/', views.rediction_2, name='app4-5'),

    # ---------------- WSGIRequest ----------------
    path('wsgi-request/', views.wesgi_request, name='app4-6'),

    # ---------------- QueryDict对象 ----------------
    path('querydict/', views.querydict, name='app4-7'),

    # ---------------- QueryDict对象 ----------------
    path('httpresponse/', views.httpresponse, name='app4-8'),
    path('jsonresponse/', views.jsonresponse, name='app4-9'),

    # 生成csv
    path('csv1/', views.csv1, name='app4-10'),
    path('csv2/', views.csv2, name='app4-11'),
    path('csv3/', views.csv3, name='app4-12'),

    # ---------------- TemplateView ----------------
    # 如果渲染的这个模版不需要传递任何参数，那么建议在url中使用TemplateView
    path('TemplateView/', TemplateView.as_view(template_name='app4/app4-4TemplateView.html'), name='app4-13'),
    # 如果即想使用 TemplateView 又想给模版提供参数呢
    path('TemplateViewAbout/', views.TemplateViewContent.as_view(), name='app4-14'),

    # ---------------- ListView ----------------
    path('ListView/', views.ArticleListView.as_view(), name='app4-15'),

    # ---------------- 给类视图添加装饰器 ----------------
    path('ArticlesView/', views.ArticlesView.as_view(), name='app4-16'),

]

django_study/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from app1 import inclued_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('app1.urls')),

    # ------------- URL与视图 -------------
    path('app1/', include('app1.urls', namespace='app1-a')),
    # 实例命名空间: 同一个app1下出现了两个实例app1、app1-1
    path('app1-1/', include('app1.urls', namespace='app1-b')),
    # 将 子URL 放到 include 中
    path('app1-2/', include([
        path('include/', inclued_views.app1_inclued, name='include_path')
    ])),

    # ------------- URL与视图 -------------
    path('app2/', include('app2.urls')),

    # ------------- Django 数据库 -------------
    path('app3/', include('app3.urls')),

    # ------------- Django 视图高级 -------------
    path('app4/', include('app4.urls')),

    # ------------- Django 状态码错误处理 -------------
    path('error/', include('error.urls')),

    # ------------- Django 表单 -------------
    path('app5/', include('app5.urls')),

    # ------------- Django 文件上传 -------------
    path('app6/', include('app6.urls')),

    # ------------- Django 缓存 -------------
    path('app7/', include('app7.urls')),

    # ------------- Django cookie 和 session -------------
    path('app8/', include('app8.urls')),

    # ------------- Django 上下文处理器 -------------
    path('app9/', include('app9.urls')),

    # ------------- Django 中间件 -------------
    path('app10/', include('app10.urls')),

    # ------------- Django CSRF攻击 -------------
    path('app11/', include('app11.urls')),

    # ------------- Django XXS攻击 -------------
    path('app12/', include('app12.urls')),

    # ------------- Django 验证和授权（一） -------------
    path('app13/', include('app13.urls')),

    # ------------- Django rest_framework -------------
    path('app14/', include('app14.urls')),

    # ------------- Django 验证和授权（二） -------------
    path('app15/', include('app15.urls')),

    # ------------- 页面显示Markdown -------------
    path('app16/', include('app16.urls')),

    # ------------- Django 日志 -------------
    path('app17/', include('app17.urls')),

    # ------------- Django 信号 -------------
    path('app18/', include('app18.urls')),

    # ------------- FastDFS -------------
    path('app19/', include('app19.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from app14.urls import router as app14

restful_url = [
    path('api/app14/', include(app14.urls)),
]

urlpatterns = urlpatterns + restful_url

app4/models.py
from django.db import models


# Create your models here.


class MethodArticle(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    price = models.FloatField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'method_article'


class ViewArticel(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'view_article'

app4/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


# --------------------- method 装饰器 ---------------------

from app4.models import MethodArticle
from django.views.decorators.http import require_http_methods, require_POST, require_GET, require_safe


# require_GET = require_http_methods(['GET'])
# require_safe = require_http_methods(['GET', 'POST'])
# require_POST = require_http_methods(['POST'])

# @require_http_methods(['GET'])
@require_GET
def method_get(request):
    ''' 限制为get请求 '''
    article = MethodArticle.objects.first()
    context = {
        'method': 'GET',
        'article': article
    }

    return render(request, 'app4/app4-1method.html', context=context)


# @require_http_methods(['POST'])
@require_POST
def method_post(request):
    ''' 限制为post请求 '''
    article = MethodArticle(title='Pthon', content='This is python', price=100.1).save()
    context = {
        'method': 'POST',
        'article': article
    }

    return render(request, 'app4/app4-1method.html', context=context)


# @require_safe
@require_http_methods(['GET', 'POST'])
def method_get_post(request):
    article = 'Django Request Method'
    method = 'Dont know'
    if request.method == 'GET':
        method = 'GET'
        article = MethodArticle.objects.first()

    if request.method == 'POST':
        method = 'POST'
        article = MethodArticle(title='Pthon', content='This is python', price=100.1)

    context = {
        'method': method,
        'article': article
    }

    return render(request, 'app4/app4-1method.html', context=context)


# --------------------- method 重定向 ---------------------
from django.shortcuts import redirect


def rediction_1(request):
    username = request.GET.get('username')
    if username:
        return HttpResponse('<h1>I have a username: %s</h1>' % username)
    else:
        return redirect('app4:app4-5')


def rediction_2(request):
    next = request.GET.get('next')
    if next:
        return render(request, 'app4/app4-2rediction.html', context={'username': 'ku_rong'})
    else:
        return HttpResponse('<h1>Dont have next url</h1>')


# --------------------- WSGIRequest ---------------------
from django.core.handlers.wsgi import WSGIRequest


def wesgi_request(request):
    print(type(request))  # 结果：<class 'django.core.handlers.wsgi.WSGIRequest'>

    # 进入 django.core.handlers.wsgi.WSGIRequest

    '''
    class WSGIRequest(HttpRequest):
        def __init__(self, environ):
        ...
    
    1. WSGIRequest 继承自 HttpRequest
    '''
    # 获取浏览器发送过来的请求头
    print(request.META)
    # 获取url的完整路径
    print(request.path)  # 结果：/app4/wsgi-request/
    # 获取完整path(包括查询字符串)
    print(request.get_full_path())  # 结果：/app4/wsgi-request/?username=ku_rong
    # 获取完整的url(包括域名)
    print(request.get_raw_uri())  # 结果：http://127.0.0.1:8000/app4/wsgi-request/?username=ku_rong
    # 获取服务器域名
    print(request.get_host())  # 结果：127.0.0.1:8000
    # 判断是否使用https协议
    print(request.is_secure())  # 结果：False
    # 判断是否使用ajax发送请求
    print(request.is_ajax())  # 结果：False

    return HttpResponse('<h1>WSGIRequest</h1>')


# --------------------- QueryDict对象 ---------------------


@require_http_methods(['GET', 'POST'])
def querydict(request):
    print(type(request.GET))  # result: <class 'django.http.request.QueryDict'>
    print(type(request.POST))  # result: <class 'django.http.request.QueryDict'>

    # request.GET 和 request.POST都属于 QueryDict对象

    # get()方法

    # username1 = request.GET['username']  # 以这种方式获取，如果没有值，那么就会报错
    username2 = request.GET.get('username', 'ku_rong')  # 以这种方式获取，如果没有值，他就会将默认值ku_rong返回

    # get_list() 获取某些key值，它对应的的数据有多个的情况，例如可多选的复选框
    if request.method == 'FET':
        title, content, tags = '', '', ''
    else:
        title = request.POST.get('title')
        content = request.POST.get('content')
        tags = request.POST.getlist('tag')

    context = {
        'username': username2,
        'title': title,
        'content': content,
        'tags': tags
    }

    return render(request, 'app4/app4-3get_and_get_list.html', context=context)


# --------------------- HttpResponse 对象 ---------------------


def httpresponse(request):
    ''' HttpResponse 将要返回给浏览器的数据现包装一下再返回 '''

    # content_type 返回数据的MIME类型，默认为 text/html
    response = HttpResponse(
        content_type='text/plain;charset=utf-8')  # 将 content_type 设置为 text/plain 纯文本的类型, 并指定编码格式为utf-8
    # content 返回内容
    response.content = '<h1>Hello Django</h1>'
    # status_code 返回 http的状态吗，正常为200
    response.status_code = 200

    # 设置请求头
    response['passward'] = '960308'

    return response


import json
from django.http import JsonResponse


def jsonresponse(request):
    ku_rong = {
        'name': 'ku_rong',
        'age': 18,
    }

    # 使用普通方法发送json数据
    # ku_rong = json.dumps(ku_rong)
    # response = HttpResponse(ku_rong, content_type='application/json')
    # return response

    # 使用 JsonResponse 发送json数据
    # response = JsonResponse(ku_rong)
    # return response

    # 默认情况下 JsonResponse 只能对字典进行 dumps ，如果要对其他类型的数据 如 列表list 进行dumps 需要传递一个 safe=False 参数才行
    fruit = ['apple', 'almod', 'blackbreey', 'bluebreey']
    response = JsonResponse(fruit, safe=False)
    return response


# --------------------- 生成CSV文件 ---------------------

import csv


def csv1(request):
    response = HttpResponse(content_type='text/csv')
    # 设置headers
    response['Content-Disposition'] = "attachment;filename=abc.csv"
    # response 实现了一个方法 write，因此可以将数据写入到response中

    writer = csv.writer(response)
    writer.writerow(['username', 'age'])
    writer.writerow(['ku_rong', '18'])
    return response


from django.template import loader


def csv2(request):
    ''' 使用模版创建csv文件 '''
    response = HttpResponse(content_type='text/csv')
    # 设置headers
    response['Content-Disposition'] = "attachment;filename=abc.csv"

    # 内容
    context = {
        'rows': [['username', 'age'], ['ku_rong', 18]]
    }
    # 加载模版
    template = loader.get_template('app4/app4.txt')
    csv = template.render(context=context)

    response.content = csv

    return response


from django.http import StreamingHttpResponse


def csv3(request):
    ''' 生成大的csv文件 '''

    response = StreamingHttpResponse(content_type='text/csv')
    response['Content-Disposition'] = "attachment;filename=large.csv"
    # response.streaming_content = ("username,age\n", "ku_rong,18\n")
    # 如果圆括号中使用for in 循环，那么它就会成为一个生成器
    row = ("Row {}.{}\n".format(row, row) for row in range(1, 100000))
    response.streaming_content = row

    return response


# --------------------- TemplateView ---------------------
from django.views.generic import View, TemplateView


class TemplateViewContent(TemplateView):
    '''
    TemplateView 这个类视图是专门用来返回模版的，
    单独使用 TemplateView 只需要在urls.py 中直接映射即可，但不能够向模版传递参数

    如果既想使用 TemplateView 又想给模版传递参数，
    那么就需要继承 TemplateView 重写一个类视图

    '''

    # 必须要指定 template_name
    template_name = 'app4/app4-4TemplateView.html'

    # 必须定义 get_context_data() 方法
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = 'ku_rong'
        return context


# --------------------- TemplateView ---------------------
from django.views.generic import ListView
from app4.models import ViewArticel


class ArticleListView(ListView):
    # 指定这个列表是给哪个模型的
    model = ViewArticel
    # 指定这个列表的模板
    template_name = 'app4/app4-5ListView.html'
    # 指定这个列表一页中展示多少条数据
    paginate_by = 5
    # 指定这个列表的排序方式
    ordering = 'created'
    # 获取第几页的数据的参数名称。默认是page。
    page_kwarg = 'page'
    # 指定这个列表模型在模板中的参数名称
    context_object_name = 'articles'

    # 获取上下文的数据
    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        context['lift'] = context.get('page_obj').number - 2
        context['right'] = context.get('page_obj').number + 2
        return context

    # 如果你提取数据的时候，并不是要把所有数据都返回，那么你可以重写这个方法。将一些不需要展示的数据给过滤掉。
    def get_queryset(self):
        return ViewArticel.objects.all()


# --------------------- 给类视图添加装饰器 ---------------------
from django.utils.decorators import method_decorator

'''
两种方法装饰
1. 在dispach()方法上装饰，但是我们不会总是重写 dispath方法，因此这种方式不建议使用
2. 直接可以装饰在类上面，但是 要指定装饰的方法是dispatch
'''


# 定义一个装饰器
def info_user(func):
    def wrapper(request, *args, **kwargs):
        username = request.GET.get('username')

        if username:
            return func(request, *args, **kwargs)
        else:
            return redirect('app4:app4-15')

    return wrapper


# @method_decorator(['info_user', ...], name='dispatch') 如果有多个装饰器，还可以传递一个列表
@method_decorator(info_user, name='dispatch')  # 第二种装饰方法
class ArticlesView(View):

    def get(self, request, *args, **kwargs):
        return HttpResponse('<hq>在 dispatch 上添加装饰器</h1>')

    # 第一种装饰方法
    # django 之中，如果要装饰一个方法的话，Django 提供了一个 装饰器 method_decorator 可以使装饰方法变得安全
    @method_decorator(info_user)
    def dispatch(self, request, *args, **kwargs):
        return super(ArticlesView, self).dispatch(request, *args, **kwargs)

templates/app4/app4-1method.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Method</title>
</head>
<body>
    <h1>Django Request Method</h1>
    <h2>{{ method }}-{{ article.title }}</h2>

</body>
</html>

templates/app4/app4-2rediction.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>rediction</title>
</head>
<body>
    <h1><a href="{% url 'app4:app4-4' %}?username={{ username }}">right, go back!</a></h1>
</body>
</html>

templates/app4/app4-3get_and_get_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>get and get_list</title>
</head>
<body>
    <h1>get() ---  hello {{ username }}</h1>
    <h1>getlist()</h1>
    <form action="" method="post">
        <table>
            <tbody>
            <tr>
                <td>title</td>
                <td>
                    <input type="text" name="title">
                </td>
            </tr>
            <tr>
                <td>content</td>
                <td>
                    <input type="text" name="content">
                </td>
            </tr>
            <tr>
                <td>Tag</td>
                <td>
                    <lable>
                        python
                        <input type="checkbox" name="tag" value="python">
                    </lable>
                </td>
                <td>
                    <labler>
                        django
                        <input type="checkbox" name="tag" value="django">
                    </labler>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="submit" value="submit">
                </td>
            </tr>
            </tbody>
        </table>
    </form>
    {% if tags and title and content %}
        <h1>title: {{ title }}</h1>
        <h2>content:</h2>
        <h2>{{ content }}</h2>
        <h2>tags:</h2>
        <h2>{{ tags.0 }}, {{ tags.1 }}</h2>
    {% endif %}
</body>
</html>

templates/app4/app4-4TemplateView.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Templateview</title>
</head>
<body>
    <h1>This is TemplateView</h1>
    {% if name %}
        <h1>Hello I am {{ name }}</h1>
    {% endif %}
</body>
</html>

templates/app4/app4-5ListView.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ListView</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

</head>
<body>
<ul>
    {% for article in articles %}
        <li>{{ article.title }} {{ article.content }}</li>
    {% endfor %}
</ul>

<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="{% url 'app4:app4-15' %}?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        {% endif %}
        {% if lift <= 1 %}

        {% else %}
            <li class="page-item"><a class="page-link" href="{% url 'app4:app4-15' %}?page=1">1</a></li>
            <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
        {% endif %}


        {% for page in paginator.page_range %}
            {% if page == page_obj.number %}
                <li class="page-item active"><a class="page-link" href="{% url 'app4:app4-15' %}?page={{ page }}">{{ page }}</a></li>
            {% elif page >= lift and page <= right %}
                <li class="page-item"><a class="page-link" href="{% url 'app4:app4-15' %}?page={{ page }}">{{ page }}</a></li>
            {% else %}
            {% endif %}
        {% endfor %}

        {% if right >= paginator.num_pages %}
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
            <li class="page-item"><a class="page-link" href="{% url 'app4:app4-15' %}?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
        {% endif %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="{% url 'app4:app4-15' %}?page={{ page_obj.next_page_number }}">Next</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
        {% endif %}

    </ul>
</nav>
</body>
</html>