app1/urls.py
from django.urls import path, re_path
from django.urls import converters, register_converter


class CategoryConverter(object):
    regex = r'\w+|(\w+\+\w+)+'  # 这里的正则表达式 变量名称 必须是 regex 不然Django不能识别

    def to_python(self, value):
        '''
        将 python+django+flask 处理成 ['python', 'django', 'flask']
        '''
        result = value.split('+')
        return result

    def to_url(self, value):
        '''
        将 ['python', 'django', 'flask'] 处理成 python+django+flask
        '''
        if isinstance(value, list):
            result = '+'.join(value)
            return result
        else:
            raise RuntimeError('转换URL的时候分类参数必须为list类型')


register_converter(CategoryConverter, 'cate')  # 将自定义的转换通过 register_converter 器注册到 Django 命名为 cate

from app1 import views

app_name = 'app1'

urlpatterns = [
    path('', views.index_django_study, name='django_study_index'),
    path('index/', views.index, name='index'),

    # url中传递参数给视图函数
    path('args-1/<int:id>/', views.url_args1, name='args-1'),
    path('args-2/', views.url_args2, name='args-2'),

    # url命名与url反转
    path('args-3/', views.url_args3, name='args-3'),
    path('args-4/', views.url_args4, name='args-4'),
    path('args-5/', views.url_args5, name='args-5'),

    # 实例命名空间
    path('args-6/', views.url_args6, name='args-6'),
    path('args-7/', views.url_args7, name='args-7'),

    # 使用re_path
    re_path(r're_path/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/', views.url_args8, name='re-path'),

    # url带参数反转
    path('args-9/', views.url_args9, name='args-9'),
    path('args-10/<int:id>/<int:page>/', views.url_args10, name='args-10'),

    # url携带查询字符串参数反转
    path('args-11/', views.url_args11, name='args-11'),
    path('args-12/', views.url_args12, name='args-12'),

    # 自定义path转换器
    path('args-13/<cate:categories>/', views.url_args13, name='args-13'),
    path('args-14/', views.url_args14, name='args-14'),

    # URL映射的时候指定默认参数
    path('args-15/<int:page>/', views.url_args15, name='args-15'),
    path('args-15-1/', views.url_args15, name='args-15-1'),

]

app9/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from app9 import views

app_name = 'app9'
urlpatterns = [
    path('app9-1/', views.app9_1, name='app9-1'),
    path('app9-2/', views.app9_2, name='app9-2'),
    path('app9-2/', views.App9View1.as_view(), name='app9-2'),
    path('app9-3/', views.App9View2.as_view(), name='app9-3'),
]

django_study/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from app1 import inclued_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('app1.urls')),

    # ------------- URL与视图 -------------
    path('app1/', include('app1.urls', namespace='app1-a')),
    # 实例命名空间: 同一个app1下出现了两个实例app1、app1-1
    path('app1-1/', include('app1.urls', namespace='app1-b')),
    # 将 子URL 放到 include 中
    path('app1-2/', include([
        path('include/', inclued_views.app1_inclued, name='include_path')
    ])),

    # ------------- URL与视图 -------------
    path('app2/', include('app2.urls')),

    # ------------- Django 数据库 -------------
    path('app3/', include('app3.urls')),

    # ------------- Django 视图高级 -------------
    path('app4/', include('app4.urls')),

    # ------------- Django 状态码错误处理 -------------
    path('error/', include('error.urls')),

    # ------------- Django 表单 -------------
    path('app5/', include('app5.urls')),

    # ------------- Django 文件上传 -------------
    path('app6/', include('app6.urls')),

    # ------------- Django 缓存 -------------
    path('app7/', include('app7.urls')),

    # ------------- Django cookie 和 session -------------
    path('app8/', include('app8.urls')),

    # ------------- Django 上下文处理器 -------------
    path('app9/', include('app9.urls')),

    # ------------- Django 中间件 -------------
    path('app10/', include('app10.urls')),

    # ------------- Django CSRF攻击 -------------
    path('app11/', include('app11.urls')),

    # ------------- Django XXS攻击 -------------
    path('app12/', include('app12.urls')),

    # ------------- Django 验证和授权（一） -------------
    path('app13/', include('app13.urls')),

    # ------------- Django rest_framework -------------
    path('app14/', include('app14.urls')),

    # ------------- Django 验证和授权（二） -------------
    path('app15/', include('app15.urls')),

    # ------------- 页面显示Markdown -------------
    path('app16/', include('app16.urls')),

    # ------------- Django 日志 -------------
    path('app17/', include('app17.urls')),

    # ------------- Django 信号 -------------
    path('app18/', include('app18.urls')),

    # ------------- FastDFS -------------
    path('app19/', include('app19.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from app14.urls import router as app14

restful_url = [
    path('api/app14/', include(app14.urls)),
]

urlpatterns = urlpatterns + restful_url

app9/models.py
from django.db import models


# Create your models here.


class App9User(models.Model):
    name = models.CharField(max_length=16)
    pwd = models.CharField(max_length=16)
    phone = models.CharField(max_length=11)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'app9_user'

app9/forms.py
from django import forms

from app9.models import App9User


class App9From1(forms.ModelForm):
    pwd1 = forms.CharField(max_length=16, min_length=6)

    def clean(self):
        clean_data = super().clean()
        pwd1 = clean_data.get('pwd1')
        pwd = clean_data.get('pwd')
        if pwd1 != pwd:
            raise forms.ValidationError('两次密码不一致')
        else:
            return clean_data

    class Meta:
        model = App9User
        fields = '__all__'


class App9Form2(forms.ModelForm):
    class Meta:
        model = App9User
        fields = ['name', 'pwd']

app9/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.contrib import messages

from app9.forms import App9From1, App9Form2
from app9.models import App9User


# Create your views here.


def app9_1(request):
    context = {}
    # user_id = request.session.get('user')
    # user = App9User.objects.get(pk=user_id)
    # context['username'] = user.name

    user = App9User.objects.all()
    if user:
        # 消息
        # 添加消息的第一种方式
        messages.add_message(request, messages.INFO, 'Hello i am a message!')  # 第一个参数是request，第二个是消息的级别，第三个是消息内容
        # 添加消息的第二种方式
        messages.info(request, "hello i'm a new message")  # 这种方式就免了消息级别的手动添加
    return render(request, 'app9/app9-1用户系统案例1.html', context=context)


# app9-1用户系统案例1

def app9_2(request):
    if request.method == 'GET':
        return render(request, 'app9/app9-4一部分Django默认上下文处理器.html')
    else:
        # 消息
        # 添加消息的第一种方式
        messages.add_message(request, messages.INFO, 'Hello i am a message!')  # 第一个参数是request，第二个是消息的级别，第三个是消息内容
        # 添加消息的第二种方式
        messages.info(request, "hello i'm a new message")  # 这种方式就免了消息级别的手动添加
        return render(request, 'app9/app9-4一部分Django默认上下文处理器.html')


class App9View1(View):

    def get(self, request):
        return render(request, 'app9/app9-2用户系统案例2.html')

    def post(self, request):
        form = App9From1(request.POST)
        if form.is_valid():
            form.save()
            return redirect('app9:app9-1')
        else:
            return render(request, 'app9/app9-2用户系统案例2.html', {'message': 'register failed!'})


class App9View2(View):
    def get(self, request):
        return render(request, 'app9/app9-3用户系统案例3.html')

    def post(self, request):
        form = App9Form2(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            pwd = form.cleaned_data.get('pwd')
            user = App9User.objects.filter(name=name, pwd=pwd).first()
            if user:
                request.session['user'] = user.id
                return redirect('app9:app9-1')
            else:
                return redirect('app9:app9-3')
        else:
            return redirect('app9:app9-3')

templates/app9/app9-1用户系统案例1.html
{% extends 'app9/app9-base.html' %}

{% block body %}
    <div style="text-align: center">
    <h1>This is Index</h1>
    {% if username %}
        <h2>Hello {{ username }}</h2>
    {% endif %}
    <h1>django.template.context_processors.debug</h1><p>{{ debug }} {{ sql_queries }}</p>
    <h1>django.template.context_processors.request</h1><p>{{ request }}</p>
    <h1>django.contrib.auth.context_processors.auth</h1><p>{{ user }}</p>
    <h1>django.contrib.messages.context_processors.messages</h1>{{ messages }}<p></p>
    {% for message in messages %}
        {{ message }}
    {% endfor %}

    </div>
{% endblock %}

templates/app9/app9-2用户系统案例2.html
{% extends 'app9/app9-base.html' %}

{% block body %}

    <div style="text-align: center">
        <h1>This is Register</h1>
        <form action="" method="post">
            <table>
                <tbody>
                <tr>
                    <td>name</td>
                    <td>
                        <input type="text" name="name">
                    </td>
                </tr>
                <tr>
                    <td>phone</td>
                    <td>
                        <input type="text" name="phone">
                    </td>
                </tr>
                <tr>
                    <td>pwd</td>
                    <td>
                        <input type="password" name="pwd">
                    </td>
                </tr>
                <tr>
                    <td>pwd again</td>
                    <td>
                        <input type="password" name="pwd1">
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="submit">
                    </td>
                </tr>
                </tbody>
            </table>
        </form>
        {% if message %}
            <p>{{ message }}</p>
        {% endif %}
    </div>
{% endblock %}

templates/app9/app9-3用户系统案例3.html
{% extends 'app9/app9-base.html' %}

{% block body %}

    <div style="text-align: center">
        <h1>This is Login</h1>
        <form action="" method="post">
            <table>
                <tbody>
                <tr>
                    <td>name</td>
                    <td>
                        <input type="text" name="name">
                    </td>
                </tr>
                <tr>
                    <td>pwd</td>
                    <td>
                        <input type="password" name="pwd">
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="submit">
                    </td>
                </tr>
                </tbody>
            </table>
        </form>
    </div>
{% endblock %}

templates/app9/app9-4一部分Django默认上下文处理器.html
{% extends 'app9/app9-base.html' %}

{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        <input type="text" name="name">
        <input type="submit" value="submit">
    </form>
    <div>
        <h1>django.contrib.messages.context_processors.messages</h1>
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
        <h1>django.template.context_processors.media</h1>
        <img src="{{ MEDIA_URL }}django.png" alt="">
        <h1>django.template.context_processors.static</h1>
        <script type="text/javascript" src="{{ STATIC_URL }}app9/js/app9-4.js"></script>
    </div>
{% endblock %}

templates/app9/app9-base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户系统案例</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">


</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'app9:app9-1' %}">ku_rong</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'app9:app9-1' %}">Home <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="navbar-nav navbar-right">
            {% if username %}
                <li class="nav-item">
                    <a class="nav-link" href="#">{{ username }}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app9:app9-3' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app9:app9-2' %}">Sign in</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% block body %}

{% endblock %}

</body>
</html>